name: docker-compose-push
description: Push to repository with docker-compose
inputs:
  compose_file:
    description: "absolute file path to compose file"
    required: true
  service_name:
    description: "The name of the service to push"
    required: true
  tags:
    description: "tags to push"
    required: true

runs:
  using: "composite"
  steps:
    - name: Docker compose push
      shell: bash
      run: |
        echo "starting"
        serviceImage=$(yq  -r '.services.${{ inputs.service_name }}.image' ${{ inputs.compose_file}})
        echo "serviceImage: ${serviceImage}"

        substr=":"
        baseImage=${serviceImage%%$substr*}
        echo "baseImage: ${baseImage}"
        
        declare -a tagArray=($tags)
        echo "array length: ${tagArray[@]}"

        for element in "${tagArray[@]}"; do echo $element; done 

        for element in "${tagArray[@]}"; do
          imageTagName="${baseImage}:${element}"
          docker tag $serviceImage $imageTagName
          echo "pushing ${imageTagName}"
          docker push ${imageTagName}
        done
