name: docker-compose-push
description: Push to repository with docker-compose
inputs:
  compose_file:
    description: "absolute file path to compose file"
    required: true
  service_name:
    description: "The name of the service to push"
    required: true
  
  tags:
    description: "tags to push"
    required: false

runs:
  using: "composite"
  steps:
    # - name: Docker compose push
    #   shell: bash
    #   run: |
    #     delimiter=" "
    #     declare -a array=(${{ inputs.tags}})
    #     for element in "${array[@]}"; 
    #       do additional_compose_command="$additional_compose_command -f "$element;
    #       docker-compose -f ${{ inputs.compose_file }} push 
    #     done

    #     docker-compose -f ${{ inputs.compose_file }} $additional_compose_command run --rm ${{ inputs.test_service_name }}

    # - name: Docker compose push
    #   shell: bash
    #   run: docker-compose -f ${{ inputs.compose_file }} push

    - name: Docker compose push
      shell: bash
      run: |
        image=$(yq  -r '.services.${{ inputs.service_name }}.image' ${{ inputs.compose_file}})
        echo $image
