name: script-remote-action
description: Runs a remote hello world script
runs:
  using: "composite"
  steps:
    - name: Run script
      shell: bash
      run: |
        chmod +x ./tools/script-remote-action/hello.sh
        ./tools/script-remote-action/hello.sh

