name: script-remote-action
description: Runs a remote hello world script
inputs:
  file_name:
    description: .sh file to execute
    type: string
    required: true
  file_path:
    description: path to executable (terminate with /)
    type: string
    default: ./

  
runs:
  using: "composite"
  steps:
    - name: Run script
      shell: bash
      run: |
        chmod +x ${{ inputs.file_path }}${{ inputs.file_name }}
        ${{ inputs.file_path }}${{ inputs.file_name }}

