name: docker-compose-test
description: Testing with docker-compose
inputs:
  compose_file:
    description: "absolute file path to compose file"
    required: true
  
  additional_compose_files:
    description: "absolute file paths to additional compose files"
    required: false

runs:
  using: "composite"
  steps:
    - name: Echo command
      shell: bash
      run: |
        additional_compose_command=""
        delimiter=" "
        declare -a array=($(echo ${{ inputs.additional_compose_files}} | tr "$delimiter" " "))
        for element in "${array[@]}"; do additional_compose_command="$additional_compose_command -f "$element; done

        echo docker-compose -f ${{ inputs.compose_file }} $additional_compose_command build
    # - name: Docker compose build
    #   shell: bash
    #   run: docker-compose -f ${{ inputs.compose_file }} build
