name: docker-login
description: Log in to docker registry
inputs:
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true
  registry_url:
    description: "Base url for registry"
    required: true
    # options:
    #   - docker.io
    #   - ghcr.io
    #   - registry.gitlab.com
    #   - <registry-name>.azurecr.io
    #   - <aws-account-number>.dkr.ecr.<region>.amazonaws.com
    #   - public.ecr.aws

runs:
  using: "composite"
  steps:
    - name: Login to the Registry
      uses: docker/login-action@v1
      with:
        username: ${{inputs.registry_username}}
        password: ${{inputs.registry_password}}
        registry: ${{inputs.registry_url}}
