name: hello-you-workflow

on: 
  workflow_call:
    inputs:
      name:
        description: name to greet
        type: string
        required: true

jobs:
  example:
    name:  Hello you reusable workflow
    runs-on: ubuntu-latest
    
    steps:
    - name: hello you remote action
      uses: Tsanton/templates/hello-you-remote-action@master
      with:
        name: ${{ inputs.name }}