name: hello-you-remote-workflow

on: 
  workflow_call:
    inputs:
      name:
        description: name to greet
        type: string
        required: true

jobs:
  example:
    name:  Hello you remote workflow
    runs-on: ubuntu-latest
    
    steps:
    - name: hello you remote action
      uses: Tsanton/templates/@master/hello-you-remote-action
      with:
        name: ${{ inputs.name }}